num_epochs: 200  # 总迭代轮次
save_freq: 1 # 每多少轮存入 tensorboard
batch_size: 64 # 每批训练大小

dataset:
    dataset_name: aclImdb
    path: /home/yf/dataset/gnn

model:
    name: text_gnn
    checkpoint_dir: ./_checkpoint
    num_hidden: 4  # Number of units in hidden layer 1.
    learning_rate: 0.02 # 学习率
    num_layers: 2 # 隐藏层层数
    keep_pro: 0.5 # dropout保留比例
    weight_decay: 5e-4 # L2 regularization