num_epochs: 10  # 总迭代轮次
save_freq: 1 # 每多少轮存入 tensorboard
batch_size: 64 # 每批训练大小

dataset:
    dataset_name: aclImdb
    data_generator: multiple_file_data_generator
    path: dataset/aclImdb/info.yaml
    seq_length: 120  # 序列长度

model:
    name: text_rnn
    checkpoint_dir: ./_checkpoint
    num_filters: 1024  # 卷积核数目
    hidden_size: 30  # 全连接卷积数量卷积核数目
    kernel_size:   # 卷积核尺寸
    learning_rate: 1e-3  # 学习率
    num_layers: 1 # 隐藏层层数
    rnn_type: gru # lstm 或 gru
    keep_pro: 0.5 # dropout保留比例
